Improve format handling in GStreamer caps
renesas-rcar/gst-plugin-vspfilter pull request #1
Opened 2016-12-08 23:42 UTC by petr-nechaev

Explicit specification of formats in capabilities improves user experience.
NV16 support is crucial for converting video from VIN modules.

2017-08-13 16:28 UTC, petr-nechaev commented
Hello @ywakasawa , @dhobsong . Could you please merge this pull request?

2017-08-14 01:18 UTC, dhobsong commented
Hi @petr-nechaev .  Thank you for these patches. 
I don't have write access for this repo and @ywakasawa will be on vacation until next week.
I had some minor comments though, so I will add those inline.

2017-08-14 01:25 UTC, dhobsong requested changes

2017-08-14 01:25 UTC, dhobsong commented on gst/vspfilter/gstvspfilter.c
> +        "height = [ 1, 8192 ], " \
According to the spec sheet, the maximum width and height is 8190, not 8192.

2017-08-14 01:25 UTC, dhobsong commented on gst/vspfilter/gstvspfilter.c
> +        "height = [ 1, 8192 ], " \
Is the "(experimental)" tag here needed?  Offhand I can't see any reason why this shouldn't work. Have you noticed some potential problems with the NV16 support?

2017-11-16 13:01 UTC, petr-nechaev commented
Thank you for accepting changes. Sorry for delay - had no time to fix the patch

2017-11-16 13:01 UTC, closed without merging